server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
#      serve para dropar e criar bancos automaticamente quando a aplicacao é
#      pausada ou inicializada
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

