server:
  port: 8090

spring:
  spring:
    kafka:
      bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
      topic:
        orchestrator: orchestrator
        product-validation-success: product-validation-success
        product-validation-fail: product-validation-fail

    consumer:
        group-id: product-validation-group
        auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-db
    username: postgres
    password: postgres

  jpa:
    hibernate:
#      serve para dropar e criar bancos automaticamente quando a aplicacao é
#      pausada ou inicializada
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: off